### ISSUE TITLE
BBBW not stopping

### ISSUE THREAD

**Issue by rafaeltgross** [bigjosh/bbbrtc#1]
I have 2 BBBW and at both the software is hanging at
Stopping RTC...waiting for stop...

what sould I do?

thanks
Rafael

**Comment by bigjosh** [comment]
Linux version?

**Comment by rafaeltgross** [comment]
8.7

**Comment by bigjosh** [comment]
You are running as root? Can you check kernel version with `uname -r`?

**Comment by rafaeltgross** [comment]
Hi,

Thanks. Yes I was running as root. *uname -r* is 4.4.54-ti-r93

Regards,
Rafael

**Comment by bigjosh** [comment]
It looks like the 4.x kernels break this fix by locking the MDIO registers. I only use the 3.x kernels because of issues with the PRUSS subsystem in the newer ones. If you use the PRU, I’d recommend sticking with 3.x. If you need to use a 4.x kernel and are willing to invest some time figuring out what hoops they need you to jump though to access these registers, LMK because there are others who would benefit from this work as well. Thanks!

**Comment by rafaeltgross** [comment]
Hi Josh,

I would like very much to run it on kernel 4.x. but I have no Idea where to
start from.
Witch operating system are you running your Beaglebone? and witch kernel
exactly?

thanks again and regards
rafael

**Comment by bigjosh** [comment]
I use `3.8.13-bone80` which is in `Debian 4.6.3-14` which I think you can download as `Debian 7.11 ` from [here](https://beagleboard.org/latest-images). (So many version numbers! :) )

**Comment by bigjosh** [comment]
...and just curious why you prefer the 4.x kernel?

**Comment by rafaeltgross** [comment]
Because I use BBBW and BBBlue witch isn't supported by Debian 7.11.
It will be great to have your magic wake system running on 4.x Kernel
Thanks,
Rafael

**Comment by bigjosh** [comment]
Really? The BB Blue uses the same processor as the BBB so I'd expect the older version to work with it. Maybe there are just some drives missing form the older distro that could be added?

You are not the only one who would like to see this running on the newer kernel, but realistically I will not have to to figure this out. I'd be happy to help anyone who did give it a try though, and would gratefully accept a Pull Request with the new code from them!

**Comment by bigjosh** [comment]
Closed with 3867056805c8768373172621f944d2888e8592e2
